credentials:
  usernames:
    djuniow:
      email: djalmaluis@correios.com.br
      name: Djalma Luis
      password: abc
cookie:
  expiry_days: 30
  key: emu
  name: random
pre-authorized:
  email:
    - melsby@gmail.com